//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public System.DateTime Login { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Logout { get; set; }
        public byte Mode { get; set; }
        public int ComputerId { get; set; }
        public bool Weekend { get; set; }
    
        public virtual Computer Computer { get; set; }
    }
}
