//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAMS_DatabaseEntities : DbContext
    {
        public CAMS_DatabaseEntities()
            : base("name=CAMS_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Computer> Computers { get; set; }
        public virtual DbSet<ComputerLab> ComputerLabs { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDepartment> UserDepartments { get; set; }
    }
}
